# Usar a imagem do Nginx
FROM nginx:alpine

# Copiar os arquivos de configuração do Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar o conteúdo da aplicação (HTML, JS)
COPY . /usr/share/nginx/html

EXPOSE 80
