apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS todos;
    USE todos;
CREATE TABLE IF NOT EXISTS todos (
  _id int NOT NULL,
  todo varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO todos (_id, todo) VALUES
(1, 'Acordar as 7h'),
(2, 'Ir a aula as 8h.'),
(3, 'almoçar as 12h'),
(4, 'ir a aula as 14h'),
(5, 'apresentar esse exemplo');

ALTER TABLE todos
  ADD PRIMARY KEY (_id);


ALTER TABLE todos
  MODIFY _id int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;